#!/usr/bin/env bash
MINECRAFT_VERSION="1.19.3"
# MINECRAFT_VERSION="1.19.2"
# MINECRAFT_VERSION="1.19.1"
SPIGOT_BUILD_TOOLS_JAR_URL="https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"

bake_task install-spigot
function install-spigot () {
    set -x
    test -d ./spigot || mkdir ./spigot
    (
        cd ./spigot
        test -f BuildTools.jar || curl -o BuildTools.jar "$SPIGOT_BUILD_TOOLS_JAR_URL"
        if [[ ! -f "spigot-$MINECRAFT_VERSION.jar" ]]; then
            if ! java -Xmx2G -jar BuildTools.jar --rev "$MINECRAFT_VERSION"; then
                curl -o BuildTools.jar "https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"
                java -Xmx2G -jar BuildTools.jar --rev "$MINECRAFT_VERSION"
            fi
        fi

        # https://download.getbukkit.org/craftbukkit/craftbukkit-1.19.2.jar
        # krb-minerepl-bukkit/lib/craftbukkit-1.19.2.jar
        if [[ ! -f "krb-minerepl-bukkit/lib/craftbukkit-$MINECRAFT_VERSION.jar" ]]; then
                curl -o "krb-minerepl-bukkit/lib/craftbukkit-$MINECRAFT_VERSION.jar" "https://download.getbukkit.org/craftbukkit/craftbukkit-$MINECRAFT_VERSION.jar"
        fi
    )

    if [[ ! -e "$PWD/spigot/krb-minerepl-bukkit/lib/spigot-$MINECRAFT_VERSION.jar" ]]; then
        ln -s "$PWD/spigot/spigot-$MINECRAFT_VERSION.jar" "$PWD/spigot/krb-minerepl-bukkit/lib/spigot-$MINECRAFT_VERSION.jar"
    fi
}


bake_task run-spigot "Run the bukket/spigot server"
function run-spigot () {
    set -x
    (
        cd ./spigot/krb-minerepl-bukkit
        lein classpath | tr : "\\n" | grep .m2/repository | tr "\\n" : | sed 's/:$//' > ../cp.out
    )
    (
        cd ./spigot
        export CLASSPATH="$(cat cp.out)"
        # java -cp "$CLASSPATH" -Xmx2G -jar "spigot-$MINECRAFT_VERSION.jar"
        # java -cp "$CLASSPATH:spigot-$MINECRAFT_VERSION.jar" -Xmx4G org.bukkit.craftbukkit.Main nogui
        # java -cp "$CLASSPATH:spigot-$MINECRAFT_VERSION.jar" -Xmx4G # org.bukkit.craftbukkit.Main nogui
        java -cp "$CLASSPATH:./krb-minerepl-bukkit/lib/craftbukkit-$MINECRAFT_VERSION.jar" -Xmx8G org.bukkit.craftbukkit.bootstrap.Main nogui
    )
}


bake_task build_plugin
function build_plugin () {
    (
        cd ./spigot/krb-minerepl-bukkit
        # lein javac
        lein uberjar
    )

    (
        cd ./spigot
	      test -d ./plugins || mkdir ./plugins
        cp krb-minerepl-bukkit/target/krb-minerepl-bukkit-0.1.0-SNAPSHOT-standalone.jar ./plugins/
    )
}
